### ISSUE TITLE
Add Sahih international in English and Muhammad Junagarhi in Urdu 

### ISSUE THREAD

**Issue by Sagarparvizali** [Waqar144/quran_memorization_helper#4]
English Translation
. Sahil international

Urdu Translation
. Muhammad Junagarhi

**Comment by Gamer750** [comment]
Please also add Clear Quran translation. Please make the app offline

**Comment by Waqar144** [comment]
The app is completely offline already. 

Regarding more translations, initially I didn't want to add any translation at all because there are already a lot of great apps that provide this feature. But I added it later for quick reference while reciting the Quran. The reason there is Urdu translation only is because 16-line Quran format is only used in Pakistan as far as I know and Urdu is our main language, but I don't know if all users of my app are Pakistani or not.

Adding more translations is easy, but it will bloat the app (increase app size). However, more translations can be made available via a 1 time download from https://tanzil.net/trans/ or some other resource, but that requires internet access. Alternatively, I can add a button that takes you to quran.com where you can explore other translations/tafseer.

**Comment by Gamer750** [comment]
> The app is completely offline already.
> 
> Regarding more translations, initially I didn't want to add any translation at all because there are already a lot of great apps that provide this feature. But I added it later for quick reference while reciting the Quran. The reason there is Urdu translation only is because 16-line Quran format is only used in Pakistan as far as I know and Urdu is our main language, but I don't know if all users of my app are Pakistani or not.
> 
> Adding more translations is easy, but it will bloat the app (increase app size) which is something I want to avoid. However, more translations can be made available via a 1 time download from https://tanzil.net/trans/ or some other resource, but that requires internet access. Alternatively, I can add a button that takes you to quran.com where you can explore other translations/tafseer.

It would be good if there is a feature to import translation

**Comment by Sagarparvizali** [comment]
Absolutely, I agree with you. There is already an Urdu translation included in the app. Could you please identify whose translation it is? To maintain consistency among Qur'ān apps, you should either add the default Urdu translation by Muhammad Junagarhi or remove all translations altogether."

**Comment by Gamer750** [comment]
It would be good if there is a feature to import translation from storage
